import type { Metadata } from "next";
import { Roboto_Condensed } from "next/font/google";
import "bootstrap/dist/css/bootstrap.css";
import "@/public/css/style.css";
import BaseLayout from "../components/baseLayout";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const roboto = Roboto_Condensed({
  weight: ["400", "600", "700"],
  subsets: ["latin"],
  display: "swap",
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <BaseLayout>
          {children}
        </BaseLayout>
      </body>
    </html>
  );
}
